# Generated by Django 6.0.5 on 2026-05-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'School Admin'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='admin', max_length=20),
        ),
    ]
