# Generated by Django 6.0.5 on 2026-05-16 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('admission_number', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('aadhaar_last4', models.CharField(blank=True, help_text='Last 4 digits only — full Aadhaar encrypted in v2.', max_length=4)),
                ('photo_url', models.URLField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=6)),
                ('address', models.TextField(blank=True)),
                ('parent1_name', models.CharField(blank=True, max_length=200)),
                ('parent1_phone', models.CharField(blank=True, max_length=20)),
                ('parent1_relation', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=20)),
                ('parent1_email', models.EmailField(blank=True, max_length=254)),
                ('parent1_whatsapp', models.BooleanField(default=True)),
                ('parent2_name', models.CharField(blank=True, max_length=200)),
                ('parent2_phone', models.CharField(blank=True, max_length=20)),
                ('parent2_relation', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=20)),
                ('parent2_email', models.EmailField(blank=True, max_length=254)),
                ('parent2_whatsapp', models.BooleanField(default=False)),
                ('primary_whatsapp_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('admission_date', models.DateField()),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['school', 'status'], name='students_school__cf14c8_idx'), models.Index(fields=['first_name', 'last_name'], name='students_first_n_ce3d36_idx')],
                'unique_together': {('school', 'admission_number')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo_url', models.URLField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['school', 'status'], name='teachers_school__e4cade_idx'), models.Index(fields=['first_name', 'last_name'], name='teachers_first_n_4a8b29_idx')],
            },
        ),
    ]
