# Generated by Django 6.0.5 on 2026-06-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_parent_parentstudent_parent_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='app_password',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
