[mypy]
python_version = 3.12
strict = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_any_generics = True
exclude = (^|/)(migrations|\.venv)/

plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = config.settings.dev

[mypy-celery.*]
ignore_missing_imports = True

[mypy-decouple]
ignore_missing_imports = True

[mypy-factory.*]
ignore_missing_imports = True

[mypy-weasyprint.*]
ignore_missing_imports = True
