[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
testpaths = apps tests
addopts = -ra --strict-markers --tb=short
filterwarnings =
    ignore::DeprecationWarning
markers =
    integration: integration tests that touch the database
