# Generated by Django 6.0.5 on 2026-05-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'academic_year'), name='uniq_active_enrollment_per_year'),
        ),
    ]
