# Generated by Django 6.0.5 on 2026-05-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_parent_parentstudent_parent_students_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('attendance', 'Attendance'), ('marks', 'Marks'), ('fee', 'Fee'), ('announcement', 'Announcement'), ('test', 'Test')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('link_to', models.CharField(blank=True, max_length=120)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='people.student')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['is_read', '-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'is_read'], name='notificatio_student_67112a_idx'), models.Index(fields=['school', '-created_at'], name='notificatio_school__08b728_idx')],
            },
        ),
    ]
