# Generated by Django 6.0.5 on 2026-05-30 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_studentenrollment_unique_together_and_more'),
        ('communications', '0002_notification_expires_at'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('school', 'School'), ('class', 'Class'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('fee', 'Fee')], max_length=16)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academics.class')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academics.section')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['school', '-date'], name='announcemen_school__a152bd_idx'), models.Index(fields=['target_class', '-date'], name='announcemen_target__559093_idx'), models.Index(fields=['target_section', '-date'], name='announcemen_target__87f767_idx')],
            },
        ),
    ]
