# Generated by Django 6.0.5 on 2026-06-13 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_announcement"),
        ("people", "0002_parent_parentstudent_parent_students_and_more"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementTeacherRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_reads",
                        to="communications.announcement",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_reads",
                        to="people.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "announcement_teacher_reads",
                "indexes": [
                    models.Index(
                        fields=["teacher", "announcement"],
                        name="announcemen_teacher_df4fda_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("announcement", "teacher"),
                        name="uniq_announcement_teacher_read",
                    )
                ],
            },
        ),
    ]
