# Generated by Django 6.0.5 on 2026-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_announcementteacherread'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='recipient_type',
            field=models.CharField(choices=[('parents', 'Parents'), ('teachers', 'Teachers'), ('everyone', 'Everyone')], default='everyone', max_length=16),
        ),
    ]
