# Generated by Django 6.0.5 on 2026-05-18 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_studentenrollment_unique_together_and_more'),
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='schools.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'db_table': 'fee_structures',
                'ordering': ['class_obj__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('amount_paise', models.PositiveBigIntegerField()),
                ('due_date', models.DateField()),
                ('is_optional', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='fees.feestructure')),
            ],
            options={
                'db_table': 'fee_components',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_label', models.CharField(max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_counters', to='schools.school')),
            ],
            options={
                'db_table': 'receipt_counters',
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_paise', models.PositiveBigIntegerField(default=0)),
                ('discount_paise', models.PositiveBigIntegerField(default=0)),
                ('final_paise', models.PositiveBigIntegerField(default=0)),
                ('paid_paise', models.PositiveBigIntegerField(default=0)),
                ('discount_reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=16)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='schools.academicyear')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='fees.feestructure')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='people.student')),
            ],
            options={
                'db_table': 'student_fees',
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_paise', models.PositiveBigIntegerField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank transfer'), ('online', 'Online')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('paid_on', models.DateField()),
                ('receipt_number', models.CharField(max_length=40, unique=True)),
                ('receipt_pdf_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('voided_reason', models.CharField(blank=True, max_length=200)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_voided', to=settings.AUTH_USER_MODEL)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.studentfee')),
            ],
            options={
                'db_table': 'fee_payments',
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('applied_paise', models.PositiveBigIntegerField()),
                ('paid_paise', models.PositiveBigIntegerField(default=0)),
                ('is_applicable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=16)),
                ('fee_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_components', to='fees.feecomponent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='fees.studentfee')),
            ],
            options={
                'db_table': 'student_fee_components',
                'ordering': ['fee_component__display_order'],
            },
        ),
        migrations.CreateModel(
            name='FeePaymentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount_paise', models.PositiveBigIntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fees.feepayment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student_fee_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='fees.studentfeecomponent')),
            ],
            options={
                'db_table': 'fee_payment_components',
            },
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'class_obj', 'name'), name='uniq_fee_structure'),
        ),
        migrations.AddConstraint(
            model_name='feecomponent',
            constraint=models.UniqueConstraint(fields=('fee_structure', 'name'), name='uniq_component_per_structure'),
        ),
        migrations.AddConstraint(
            model_name='receiptcounter',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year_label'), name='uniq_receipt_counter'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['school', 'status'], name='student_fee_school__cc8e95_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['academic_year', 'status'], name='student_fee_academi_8e7759_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'fee_structure'), name='uniq_student_fee_per_structure'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school', '-paid_on'], name='fee_payment_school__a00572_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['student_fee', '-paid_on'], name='fee_payment_student_418414_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfeecomponent',
            constraint=models.UniqueConstraint(fields=('student_fee', 'fee_component'), name='uniq_student_fee_component'),
        ),
        migrations.AddIndex(
            model_name='feepaymentcomponent',
            index=models.Index(fields=['payment'], name='fee_payment_payment_284d88_idx'),
        ),
        migrations.AddIndex(
            model_name='feepaymentcomponent',
            index=models.Index(fields=['student_fee_component'], name='fee_payment_student_295c95_idx'),
        ),
    ]
