# Generated by Django 6.0.5 on 2026-05-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_studentenrollment_unique_together_and_more'),
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day')], default='present', max_length=16)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to='people.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='people.student')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', 'student_id'],
                'indexes': [models.Index(fields=['school', 'date'], name='attendance_school__ee2cee_idx'), models.Index(fields=['section', 'date'], name='attendance_section_834cff_idx'), models.Index(fields=['student', 'date'], name='attendance_student_0943ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='uniq_student_date_attendance')],
            },
        ),
    ]
