# Generated by Django 6.0.5 on 2026-05-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_studentenrollment_unique_together_and_more'),
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('test_type', models.CharField(choices=[('FA1', 'Formative Assessment 1'), ('FA2', 'Formative Assessment 2'), ('FA3', 'Formative Assessment 3'), ('FA4', 'Formative Assessment 4'), ('SA1', 'Summative Assessment 1'), ('SA2', 'Summative Assessment 2'), ('OTHER', 'Other / Unit test')], default='OTHER', max_length=16)),
                ('test_date', models.DateField()),
                ('max_marks', models.PositiveSmallIntegerField()),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_created', to='people.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='academics.subject')),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['-test_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores_entered', to='people.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='people.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.test')),
            ],
            options={
                'db_table': 'test_scores',
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['school', '-test_date'], name='tests_school__8ad365_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['section', '-test_date'], name='tests_section_40504c_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['subject', '-test_date'], name='tests_subject_9bd05e_idx'),
        ),
        migrations.AddIndex(
            model_name='testscore',
            index=models.Index(fields=['test'], name='test_scores_test_id_d863ec_idx'),
        ),
        migrations.AddIndex(
            model_name='testscore',
            index=models.Index(fields=['student'], name='test_scores_student_0980ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='testscore',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='uniq_test_student_score'),
        ),
    ]
