# Generated by Django 6.0.5 on 2026-05-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='duration_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='mode',
            field=models.CharField(choices=[('offline', 'Offline (paper)'), ('online', 'Online (student-attempted)')], db_index=True, default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer')], max_length=16)),
                ('text', models.TextField()),
                ('marks', models.PositiveSmallIntegerField(default=1)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=8, null=True)),
                ('topic', models.CharField(blank=True, default='', max_length=80)),
                ('correct_answer', models.CharField(blank=True, default='', max_length=200)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.test')),
            ],
            options={
                'db_table': 'test_questions',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
            options={
                'db_table': 'test_mcq_options',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test'], name='test_questi_test_id_b6d40e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mcqoption',
            constraint=models.UniqueConstraint(fields=('question', 'display_order'), name='uniq_option_display_order'),
        ),
    ]
