# Generated by Django 6.0.5 on 2026-06-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_fix_difficulty_field'),
        ('people', '0002_parent_parentstudent_parent_students_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('term', models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('annual', 'Annual')], max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('pdf_url', models.URLField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='schools.academicyear')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards_generated', to='people.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='people.student')),
            ],
            options={
                'db_table': 'report_cards',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['student', '-published_at'], name='report_card_student_3c7c09_idx'), models.Index(fields=['school', '-published_at'], name='report_card_school__b4d09e_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year', 'term'), name='uniq_student_year_term_report')],
            },
        ),
    ]
