# Generated by Django 6.0.5 on 2026-06-07 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_reportcard'),
        ('people', '0002_parent_parentstudent_parent_students_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_marks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_marks', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_submissions', to='people.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.test')),
            ],
            options={
                'db_table': 'test_submissions',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('text_answer', models.CharField(blank=True, max_length=200)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='exams.mcqoption')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.testsubmission')),
            ],
            options={
                'db_table': 'submission_answers',
                'ordering': ['question__display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='testsubmission',
            index=models.Index(fields=['student', '-submitted_at'], name='test_submis_student_8bed33_idx'),
        ),
        migrations.AddIndex(
            model_name='testsubmission',
            index=models.Index(fields=['test'], name='test_submis_test_id_91a1b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='testsubmission',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='uniq_test_student_submission'),
        ),
        migrations.AddIndex(
            model_name='submissionanswer',
            index=models.Index(fields=['submission'], name='submission__submiss_eca6df_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='uniq_submission_question_answer'),
        ),
    ]
