# Generated by Django 6.0.5 on 2026-06-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_testsubmission_submissionanswer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard", name="term", field=models.CharField(max_length=60),
        ),
    ]
