# Generated by Django 6.0.5 on 2026-06-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_reportcard_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='pdf_published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
