# Generated by Django 6.0.5 on 2026-06-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_reportcard_pdf_published_at'),
        ('people', '0003_parent_app_password'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('subject', models.CharField(db_index=True, max_length=80)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('board', models.CharField(blank=True, default='', max_length=120)),
                ('chapter_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chapter_name', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer')], max_length=16)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='', max_length=8)),
                ('text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, default='', max_length=200)),
                ('explanation', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null = admin/global; set = teacher-private.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to='people.teacher')),
                ('school', models.ForeignKey(blank=True, help_text='Null = global SmartSkool catalog.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to='schools.school')),
            ],
            options={
                'db_table': 'bank_questions',
                'ordering': ['subject', 'chapter_number', 'id'],
                'indexes': [models.Index(fields=['subject', 'chapter_name'], name='bank_questi_subject_ca78ca_idx'), models.Index(fields=['created_by'], name='bank_questi_created_75056a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('created_by__isnull', True), models.Q(('source_id', ''), _negated=True)), fields=('source_id',), name='uniq_global_bank_source_id')],
            },
        ),
    ]
