# Generated by Django 6.0.5 on 2026-06-21 17:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_question_explanation'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', models.CharField(max_length=80)),
                ('is_series', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'db_table': 'exam_names',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='exams.examname'),
        ),
        migrations.AddIndex(
            model_name='examname',
            index=models.Index(fields=['school', 'display_order'], name='exam_names_school__6c15b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='examname',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), models.F('school'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_exam_name_label_per_school'),
        ),
    ]
